# Bot redirects for poll pages - SSR for social media crawlers
[[redirects]]
  from = "/poll/*"
  to = "/.netlify/functions/poll-ssr?id=:splat"
  status = 200
  conditions = {User-Agent = ["*bot*", "*Bot*", "*facebook*", "*Facebook*", "*kakao*", "*KAKAO*", "*twitter*", "*Twitter*", "*whatsapp*", "*WhatsApp*", "*telegram*", "*Telegram*", "*discord*", "*Discord*", "*slack*", "*Slack*", "*linkedIn*", "*LinkedIn*"]}

# SPA fallback for regular users
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (will be overridden by Netlify dashboard settings)
[context.production.environment]
  VITE_APP_URL = "https://thegoat123.com"

# Functions directory
[functions]
  directory = "netlify/functions"